import Head from 'next/head'
import { Inter } from '@next/font/google'
import HomePage from '@/components/home/Home'


const inter = Inter({ subsets: ['latin'] })

// Top Page

export default function Home({title, description, data}) {
  return (
    <>
      <Head>
        <title>Vacation hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossOrigin="anonymous" />
      </Head>  
      <HomePage title={title} description={description} data={data} />   
    </>
  )
}

export async function getServerSideProps() {

  const {destinations} =await  import('../../data/destinations.json')

  return {
      props: {
          title: 'Vacation Hub',
          description: "Your one-stop destination for all your travel needs! We are a tour and travel company that specializes in crafting memorable and unique travel experiences for our customers. Whether you're looking for a relaxing beach holiday, a thrilling adventure, or a cultural immersion, we have a range of options for you to choose from. Our expert travel advisors will work with you to tailor your itinerary to suit your interests, budget, and schedule. With our extensive network of travel partners, you can trust us to provide top-notch services and exceptional value for money. Book your next adventure with Vacation Hub and let us turn your travel dreams into reality!",
          data: destinations
      }
  }
}
