import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link  from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// Top Page

export default function Home({title, description}) {
  return (
    <>
      <Head>
        <title>Vacation hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <header className={styles.header}>
          <nav>
            <Link href="/">Home</Link>
            <a href="/about">About</a>
            <a href="/destinations">Destinations</a>
          </nav>
        </header>
        <h1 className={styles.title}> Welcome to {title} </h1>
        <p className={styles.description}>
         {description}
        </p>
        <div className={styles.grid}>
          <a href="/destinations/destination1" className={styles.card}>
            <h3>Destination One &rarr;</h3>
            <p>Find in-depth information about Destination One.</p>
          </a>
          <a href="/destinations/destination2" className={styles.card}>
            <h3>Destination Two &rarr;</h3>
            <p>Find in-depth information about Destination Two.</p>
          </a>
          <a href="/destinations/destination3" className={styles.card}>
            <h3>Destination Three &rarr;</h3>
            <p>Find in-depth information about Destination Three.</p>
          </a>
          </div>   
      </main>
    </>
  )
}

export function getServerSideProps() {
  return {
      props: {
          title: 'Vacation Hub',
          description: 'Find the best vacation spots'
      }
  }
}
